### ISSUE TITLE
Players spawning with weapons

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#1]
We've seen various equipment being spawned on certain players that join.

`fn_setBasicLoadout.sqf` might need adjustments.

**Comment by SyMP2005** [comment]
Change to global variants for this?

https://github.com/Theseus-Aegis/Olympus/blob/master/functions/fn_setBasicLoadout.sqf#L23-L29

**Comment by jonpas** [comment]
https://github.com/Theseus-Aegis/Olympus/blob/master/functions/fn_setBasicLoadout.sqf#L21

`remove*` commands only work where units are local.
