### ISSUE TITLE
Define requirements for basic weapon courses

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#10]
All need a whiteboard with the info:
- Used weapon
- Used stance
- Used TAC firing range mode
- Amount of targets
- Countdown time
- Pause duration (if applicable)
- Maximum completion time

**To do:**
- [x] Pistol course
  - **Weapon used:** MP-443 GRACH
  - **Stance:** Standing
  - **Mode:** Hit (target limit)
  - **Targets:** 30 targets
  - **Countdown:** trainee's choice
  - **Pause duration:** NA
  - **Completion:** < 45 seconds
- [x] Rifle course
  - **Weapon used:** Colt M4 Carbine with iron sights.
  - **Stance:** Crouch, NO weapon leaning
  - **Mode:** Hit (target limit)
  - **Targets:**  55 targets
  - **Countdown:** trainee's choice
  - **Pause duration:** NA
  - **Completion:** < 105 seconds
- [x] MG course
  - **Weapon used:** M249 PiP (RIS / 18.3 In.) with Aimpoint CompM2 Red Dot 
  - **Stance:** Prone with bipod deployed.
  - **Mode:** Hit (All targets)
  - **Targets:** 30
  - **Countdown:** 12/15secs
  - **Pause duration:** N/A
  - **Completion:**  <85 secs & >65% accuracy.
- [x] DMR course
  - **Weapon used:** M14 with TS-30A2 & Bipod 
  - **Stance:** Prone
  - **Mode:** Timed
  - **Targets:** NA
  - **Countdown:** trainee's choice
  - **Pause duration:** 5 seconds
  - **Completion:** > 95% Accuracy & > 40 Targets hit
- [x] Create PSD's and convert to PAA.

**Comment by Dimaslg** [comment]
For the Rifle course go with the same setup on the targets but 45 targets (I think its the maximum you can set). Personally I would remove the optics on the gun. Its the basics certs, so I would keep it simple. 

For MG I didnt think about it, I'll as danrex about it, he played always as MG and he loves it.

For the DMR apart from the prone stance I suggest add more stances, kneeling and standing, also I would add moving targets. We are not that much people and a Marksman is not gonna be alone in a hill or in a roof covering us for that much time, he is gonna move and he is gonna stick with the unit a lot of time, if we are gonna use a DMR I want it to be someone I know he can shot, because shooting with a 7.62 to standing targets being prone its not that hard.

**Comment by SyMP2005** [comment]
- You can set as many targets as you want, I just have to add them to the module. Let me know how many you want exactly.  
- We'll remove the optics and go for iron sights. (Do keep in mind how much the iron sights would obscure the view down range.)  
- DMR I wanna stick to the prone stance, because of the distance to the targets. Also stick with one stance for the actual "test". Besides, there is already not that much room up that tower.  
- As for the moving targets, I don't think this is doable with pop-ups. @jonpas can you confirm?

**Comment by Dimaslg** [comment]
- 50/55 targets would be enought, leaving 5/10 bullets to spare. I'll get you a time today.
- I had in mind that the iron sights let you less fild of vision down range.
- You can shoot the DMR on the Rifle range. 
- @jonpas?? Moving targets??

**Comment by jonpas** [comment]
> As for the moving targets, I don't think this is doable with pop-ups. @jonpas can you confirm?

Confirming, unless someone writes a script for me that won't kill performance and will nicely sync targets across all machines.

**Comment by SyMP2005** [comment]
- DMR on the rifle range? No. => Engagements at 500m+, if you can hit those i'm sure you'll be able to hit anything closer :smile:

**Comment by Dimaslg** [comment]
@jonpas could you get us the maximum targets to 50 and 55? For testing purposes.

I got this set and I think its quite enough for a Basic one, would like to test it with 50/55 targets, so if you miss some rounds, you have to reload twice and the penalty is bigger.

```
- Weapon used: Colt Carbine with iron sights.
- Stance: Crouch, **NO** weapon leaning. (leaning the weapon block you from aiming far to the sides)
- Mode: Hit (Target Limit)
- Targets: 45 (To test 50/55)
- Countdown: 6s
- Pause duration: 2s
- Completion: <90secs (Would like to test it with a couple of more people to check times)
```

Also there are some targets that get behind a bush on the left range and behind a tree on the right one.

For the left range we could delete the target or move the shooting spot to the right:
http://i.imgur.com/Dxg6Ji0.jpg
http://i.imgur.com/cZaZiJg.jpg (the screen above was taken from this new spot)

For the right range we have to remove two targets:
http://i.imgur.com/5ZXnfYs.jpg

**Comment by jonpas** [comment]
> @jonpas could you get us the maximum targets to 50 and 55? For testing purposes.

@Dimaslg That's all settable in a module, you can add more settings as you want. Either way I suggest you clone the repo and run Olympus locally, then you can modify settings as you see fit and test what you like.

**Comment by Dimaslg** [comment]
@jonpas I don't know what you are talking about.

**Comment by SyMP2005** [comment]
I'll try and push out an update by tomorrow.

**Comment by emythiel** [comment]
With the current settings I got the following:

Rifle Course: ~93 seconds.
Maybe have completion time at around 100 seconds?

Pistol Course: ~42 seconds.
Completion time at about 45-50 seconds?

**Comment by SyMP2005** [comment]
@Dimaslg approve and i'll push.

**Comment by Dimaslg** [comment]
@SyMP2005 Change the whiteboards with the next times:
- Pistol: <45 on the right lane of the range.
- Rifle: <105 on the left lane of the range.
- Grenades: Two attempts on each lane and all lanes must be passed.

For the pistol and rifle, there would be three attempts for each and we get the better time of them.

@jonpas Could it be possible to add a ranking with the names and times to the website? Nothing automatic needed, ill write down the times of the people who take the tests and ill hand you the numbers for this quarter, also would be nice if the times were on the certificates card.

**Comment by jonpas** [comment]
Talk to @Omnirock for website stuff. And anything is possible, but I have no intention of doing it (other priorities and I see no benefit from it).

**Comment by SyMP2005** [comment]
Yeah, can't just hand @jonpas the numbers @Dimaslg. We can make a page for you to write stuff down.

**Comment by Dimaslg** [comment]
Daniel Gonzalo loves MGs, Ill talk with him to get something for it this week and Ill try to arrange something for the Marksmen if theres nothing for it yet.

**Comment by Dimaslg** [comment]
Right now the DMR course is a NO GO for me, targets are all at the same range and there is nothing challenging on just aim at the targets, being prone with a bipod and a long scope, its just click, click, click, click... Could be hard adjusting it for a low completion time, but I don't think that's the solution for a DMR certification.

For MG course we got something, but we also are not happy about it. **MG is not about precision, is about some principles that must be taught and cannot be tested by shooting at some targets.**

```
- Weapon used: M249 with Aimpoint and NATO bipod.
- Stance: Prone
- Mode: Hit (All targets)
- Targets: 20 or 30 TBD
- Countdown: 12/15secs
- Pause duration: N/A
- Completion: <60 or 65 secs & >60 or 65% accuracy. 
```

I use the accuracy because we want the candidate to know how to handle ammo, not waste it, instructor must be checking candite use short burts and not tapping the targets.

**Comment by jonpas** [comment]
> - Mode: Hit (All targets)
> - Targets: 20/30

That doesn't work like that. You can't have a mode that requires hitting all targets and expect it to finish when 20 out of 30 are hit.
If you want someone to not shoot all the targets then you must set a time limit when the course will finish and display the results.

**Comment by Dimaslg** [comment]
Thats the first try on that @jonpas , with 20/30 I meant 20 or 30 targets, still TBD. Already fixed.

**Comment by jonpas** [comment]
Ah, haha, my bad! :laughing:

**Comment by Dimaslg** [comment]
**Basic Machine Gunner Course**

```
- Weapon used: M249 PiP (RIS / 18.3 In.) with Aimpoint CompM2 Red Dot 
- Stance: Prone with bipod deployed.
- Mode: Hit (All targets)
- Targets: 30
- Countdown: 12/15secs
- Pause duration: N/A
- Completion: <85 secs & >65% accuracy. 
```

**Comment by SyMP2005** [comment]
Is that final @Dimaslg?

**Comment by Dimaslg** [comment]
Yes

**Comment by System98** [comment]
Ingame board of MG-course has the required time written as <55 when it should be <85. :stuck_out_tongue:

**Comment by SyMP2005** [comment]
oh, my bad
i'll correct that asap

**Comment by Dimaslg** [comment]
Rory went hardcore with MGs :dancer:

**Comment by SyMP2005** [comment]
@System98, fixed on Olympus now
