### ISSUE TITLE
Advanced Pistol suggestion

### ISSUE THREAD

**Issue by emythiel** [Theseus-Aegis/Olympus#100]
Finally getting around to this, considering we now have a larger selection of higher caliber pistols thanks to the NIArms P226 mod.

- Pistol: SigSaur P226R Combat(.357SIG)
- Time: 50 Seconds

Since we no longer have any high caliber weapons with more ammo (originally we had ~15 or 16 iirc for the FNP45 Tactical from RH Pistols), course would need to be altered a little as well.
I'd suggest removing these 2 targets:
![107410_20180619133253_1](https://user-images.githubusercontent.com/18901520/41595195-39d6a18e-73c6-11e8-86f4-6eec013008fb.png)
Makes it possible to run through the course without having to stop and reload while staring at a target, just like with Adv. Rifle where there's never too many targets before needing to reload.
Might need to make a few more changes, but for now that would do I think.

As for time, think keeping it at 50 seconds for now is fine.

**Comment by SyMP2005** [comment]
Removed the targets.
0ff296ed3d221ebb103bcbdcb79611c7f13ff129
