### ISSUE TITLE
Olympus 2.0

### ISSUE THREAD

**Issue by emythiel** [Theseus-Aegis/Olympus#106]
Download link to the template:
https://box.saurusrex.net/public/Olympus2_Template.hebontes.zip
The template is a simple mission file with comments on the map for the different ranges.
Hover over the comments for more details. Comments include basic things like what the course should have. If you have questions, or there's errors in the comments, feel free to post on `#dev-missions` Slack channel, or comment on this issue.

If you wish to help, download the template and poke around. Please comment on this issue what you're currently building so that we don't have multiple people working on the same thing (unless you intentionally coordinate, in which case that is fine)
Also, try and not overdo things. While it's nice if things look pretty, you shouldn't add a 100 small objects to a small area just to make it more immersive - more objects leads to less performance as well as bigger mission files (longer loading times).

If you aren't comfortable working with the scripts required for the courses that is fine as well. Comment that, and when you finished the basic course, we can mark that it will need the scripts setup.
That said, at this very moment the current focus should be to make the various of ranges themselves, before we move on the actual scripting/function part.

Once you're done, send the mission file to @Kresky and he'll copy it into the main Olympus 2 mission when he has time. Note that the download template above may not be updated all the time.

Current build progress checklist:
- [x] Main Spawn Hub
- [x] Basic Rifle Range
- [x] Basic Pistol Range
- [x] Basic LMG Range
- [x] Basic Marksman Range
- [x] Basic Grenades Course
- [x] Advanced Marksman Range
- [x] Advanced Pistol Range
- [x] Advanced Rifle Range
- [x] Launcher Range
- [x] 40mm Grenade Launcher Range
- [x] Medical License Course
- [x] Combat Engineer License Course
- [x] Pilot Course - Helicopter & Plane Hub
- [x] Custom Images - Signs, Adv. Course text etc.
- [x] Lights - Let there be light
- [x] Medic Course - VABox Function with medical gear

The checklist so far only includes items that are required to bring it up to Olympus 1 - things like Squad Attack Course, CAS range etc. are left out, as priority should be on what is currently already built on Olympus 1 so that it can be replaced with version 2.

**Comment by Mike-MF** [comment]
Tyrone - Main spawn hub

**Comment by JoramD** [comment]
I'd like to do the medical course but I wont be able start for at least a few days

**Comment by emythiel** [comment]
Updated Hebontes branch.
If downloading, ignore the image errors - was made using unreleased version of TAC Resources.

**Comment by emythiel** [comment]
Closing with initial Olympus 2 push #107
