### ISSUE TITLE
Basic / Advanced drivers license course

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#11]
**INFO**
- Basic drivers license would be acquired in order to purchase / rent vehicles with < 5 seats.
- Advanced drivers license would be acquired in order to purchase / rent vehicles with > 5 seats.
- Course would exist of driving on roads in between "cones".
- Completed within the given time.
- Penalty time for hitting cones.

**Comment by Dimaslg** [comment]
This is just for purchase / rent vehicles, not for be able to drive during the missions, right? I say it because the Range Rovers we use has 8 seats. I understand that people with the licenses will have preference to drive over the ones who doesn't have it.

**Comment by SyMP2005** [comment]
Don't worry too much about this just yet, still very far off.

**Comment by Dimaslg** [comment]
ok!

**Comment by SyMP2005** [comment]
On hold for vehicle depot.

**Comment by jonpas** [comment]
Course done.
