### ISSUE TITLE
Ranges not tracking accuracy

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Olympus#123]
**Arma 3 Version:** `1.98` (stable)
**Theseus Inc. Modpack Version:** `3.22.0`
**Olympus Version:** `2.3.0` (stable)

**Mods:**
```
- Theseus Inc. Modpack
```

**Description:**
- All ranges that track accuracy/time always result with time being tracked but not the accuracy as it shows 0%.

**Steps to reproduce:**
- Run range, finish range.

**Where did the issue occur?**
- Dedicated

**Comment by jonpas** [comment]
Bug in https://github.com/Theseus-Aegis/Mods.

**Comment by jonpas** [comment]
Possible cause https://github.com/Theseus-Aegis/Mods/commit/4af44eebb3c84c97ea117656ed0be95d321ead21#diff-0640fbc20c2741f7a5d6d63761626bb8R91
