### ISSUE TITLE
Demolitions course

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#13]
As discussed with @Omnirock:

**INFO**
- Demoltions range would license contractors to use explosives in the field.
-  ~~Possibly adding 40MM grenades and 40MM underslung weapons.~~ #29

**Comment by SyMP2005** [comment]
All yours @Omnirock!

**Comment by Omnirock** [comment]
DEMO/EOD fundamentals course completed on Olympus. Further documentation will be provided at http://www.theseus-aegis.com
