### ISSUE TITLE
Preventing taking items from weapon racks

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#15]
Remove the inventory interaction from the weapon holders at the rifle range.

https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#InventoryOpened

**Comment by Omnirock** [comment]
would an invisible wall fix that?

**Comment by jonpas** [comment]
It might, but I prefer event handler solution if it will work. Can use it for anything then, not just Olympus (I am thinking of API that let's you disable inventory on vehicles dynamically... etc.).
