### ISSUE TITLE
Create RPG range

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#16]
**INFO**
- RPG course with wooden tanks?
- Has to be with distances from 100 - 300 m?
- Stuff?

**Comment by Omnirock** [comment]
I can take care of this, and put it near the demo course.

keep all the loud noises in one spot.

**Comment by SyMP2005** [comment]
:+1:

Still has to be discussed with @jonpas what the technical possibilities are.

**Comment by Omnirock** [comment]
moved to backlog until documentation is complete for DEMO/EOD

**Comment by jonpas** [comment]
> Still has to be discussed with @jonpas what the technical possibilities are.

I suggest a simple script executed on killed event on the object, the script waits a bit then removes the wreck and spawns a new vehicle in place.

I don't really see the point of having something like shooting range, you are very limited in terms of reloading and all that.

**Comment by Dimaslg** [comment]
Also we need some short of Light AT, M136 or similar. Maybe is not cheaper but its easiest to carry than an RPG + its ammo apart.

**Comment by SyMP2005** [comment]
I doubt AT is ever gonna be in the form of javelin / SPIKE launcher. Light at will be the way to go.

**Comment by Dimaslg** [comment]
Javelin? Spike Launcher? Im talking about Light AT, something like AT4, M136 or russian RPG26.

**Comment by SyMP2005** [comment]
I know what you mean, and those will be the only ones used. Right now i think we only have RPG and NLAW in mind.

**Comment by SyMP2005** [comment]
Done
