### ISSUE TITLE
Launcher range - future improvements

### ISSUE THREAD

**Issue by JoramD** [Theseus-Aegis/Olympus#160]
This is more of a reminder for myself. If anyone has more ideas feel free to message me on Slack or put them in the comments on this issue.
- [x] Add `MAAWS Mk4 Mod 1` to arsenal.
- [x] Allow targets to be reset in locally hosted multiplayer.

**Comment by jonpas** [comment]
> Allow targets to be reset in locally hosted multiplayer.

What is stopping it from working now? Looking at the [code](https://github.com/Theseus-Aegis/Olympus/blob/8f468ee6747f78d224ab1f95e09096fb3a632655/Olympus.Stratis/functions/fn_resetDamagedObjects.sqf), everything seems to allow for that, the reset action happens entirely on the client.

**Comment by JoramD** [comment]
> > Allow targets to be reset in locally hosted multiplayer.
> 
> What is stopping it from working now? Looking at the [code](https://github.com/Theseus-Aegis/Olympus/blob/8f468ee6747f78d224ab1f95e09096fb3a632655/Olympus.Stratis/functions/fn_resetDamagedObjects.sqf), everything seems to allow for that, the reset action happens entirely on the client.

[This](https://github.com/Theseus-Aegis/Olympus/blob/8f468ee6747f78d224ab1f95e09096fb3a632655/Olympus.Stratis/functions/fn_resetDamagedObjects.sqf#L21) returns true on locally hosted multiplayer as well since you are the host, stopping the interaction from being added. _I have no clue why I made it do that but_ 🤷

**Comment by jonpas** [comment]
Aaah, I see. Yes, easy fix:
- `if (isServer) then {`
- action: `if (hasInterface) then {`
