### ISSUE TITLE
Update to new mission template

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Olympus#169]
It's on the old one, JJ broke everything with 4.0.0 of mission template.

hop to.

**Comment by JoramD** [comment]
This isn't on the mission template though, nor should it be. What is broken specifically?

Also please use the issue template.

**Comment by JoramD** [comment]
Can't find anything else broken other than the PR already submitted. Did make some minor improvements

**Comment by JoramD** [comment]
Closing due to inability to use issue template
