### ISSUE TITLE
Floating Signs.

### ISSUE THREAD

**Issue by mikecorello** [Theseus-Aegis/Olympus#22]
**INFO**

Rifle Firing Range (Right Lane) sign slightly floating (064-054)

See: [click here](http://steamcommunity.com/sharedfiles/filedetails/?id=676654862)

**Comment by SyMP2005** [comment]
Will be fixed in new version.

**Comment by jonpas** [comment]
Fixed by c561fe79b5b506976d5ef28554901955c6d04c13
