### ISSUE TITLE
Create 40mm firing range

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#29]
**INFO**
After completion, allows for operating 40mm underslung rifles. 
- [x] Find location
- [x] Create range
- [x] Add targets to hit with HE
- [x] Add targets to mark with smoke

**Comment by Dimaslg** [comment]
We could use the basic rifle range and the houses that are behind it, the ones used on the marksman range. Theres no need for a special and unique range for it, just that with maybe some additions.

**Comment by SyMP2005** [comment]
No, targets are placed to close to each-other, plus it'll probably bug out with explosives blasts.
I have a defined area set up for it.

**Comment by SyMP2005** [comment]
Done
