### ISSUE TITLE
Full Armory on Olympus

### ISSUE THREAD

**Issue by Dimaslg** [Theseus-Aegis/Olympus#33]
Being on the Advanced Rifle Range, want to get a handgun to just mess around in the range and see how it works with it. Not possible due to the armory limitations.Asked JJ for his, cannot get more than 3 or 4 rifle mags and a couple for the handgun.

Same for trying to get a vest to carry more ammo or trying to get anything just to have some fun. In the basic rifle range, you can waste five mags so fast and you have to go back to get more if you didnt pass for the special crate who has the gear and if you want to change something you have to go back to that crate and change it, a waste of time.

Get full armory on every crate of Olympus, it will be easier and faster for everything. Olympus is there to do training, but also to mess around and test all the guns and gear, specially the one we cannot get on the missions, like high caliber snipers. **To have fun.**

**Comment by SyMP2005** [comment]
Added 2 separate Arsenal functions.
- `Full Arsenal` => full arsenal functionality, duh...
- `Arsenal` => certificate related weaponry.

**Comment by jonpas** [comment]
> Not possible due to the **armory** limitations.

Lies, @SyMP2005 is using **Arsenal**, comparing my Armory with vanilla Arsenal is a disgrace!

Either way, Armory supports adding "virtual" items with custom defined category and sub-category, last update added "show only compatible" sub-category as well, it should now be even better to use than Arsenal (faster and simpler).
