### ISSUE TITLE
Create teleport script

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#36]
- Create teleport script with interactable objects to teleport from one location to another.

**Comment by SyMP2005** [comment]
Added working version 8bf2d0cbdd065ac8af1c588c50199212eeb020fd

Most likely it will need some improvements @jonpas?

**Comment by jonpas** [comment]
Except that it's hard-coded locations it looks good. You can also loop through locations if you want less ~~duplicated~~ multiplicated code.

**Comment by SyMP2005** [comment]
Yeah i don't know how to do that, tried before but, yeah...

**Comment by jonpas** [comment]
Quick mock up:

```
params ["_controller"];

{
    _x params ["_teleportObject", "_text"];

    private _action = [
        format [QGVAR(%1), _teleportObject],
        ["Fast travel to", _text] joinString " ",
        "",
        {
            ACE_player setPosASL (getPosASL (_this select 2));
        },
        {true},
        {},
        _teleportObject
    ] call ACE_Interact_Menu_fnc_createAction;

    [_controller, 0, ["ACE_MainActions"], _action] call ACE_Interact_Menu_fnc_addActionToObject;
} forEach [
    [teleportPosBase, "Base"],
    [teleportPosAdvRifle, "Adv. Rifle course"],
    [teleportPosMG, "MG course"],
    [teleportPosCQB, "CQB course"],
    [teleportPosUrban, "Urban City course"]
];
```

**Comment by SyMP2005** [comment]
Yep that works! I have a couple of other things I'd like to add @jonpas, that I don't know how.
- Short fade to black and mid-screen text saying to where you're travelling. Tried with `titleCut` couldn't get it to work with the fade. 
- Also, he teleports instantly, before the fade, so I'm guessing `fnc_waitAndExecute` will be required. But I don't know how that with the passing of arguments within a call...
- Remove the possibility to teleport the area you're currently positioned.

**Comment by SyMP2005** [comment]
dc78362feb2083276d736d2d6d279bfc79d80746
