### ISSUE TITLE
Highscore notation

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#46]
Please note the top 3 high-scores for courses, per person here:

Format
`1st Name - Time`
`2nd Name - Time`
`3rd Name - Time`
- Basic Pistol
- Basic Rifle
- Basic MG
- Basic DMR
- Adv Rifle

**Comment by SyMP2005** [comment]
@dimaslg @kresky

**Comment by Dimaslg** [comment]
Advanced Rifle Course Times:

18/06/2016
K.Kresky: **77.199** sec. 100% Accuracy (49/49 Targets) **Pass**
R.Guldentops: **82.252** sec. 96% Accuracy (49/51 Targets) **Pass**
D.Lopez: **82.574** sec. 96% Accuracy (49/51 Targets) **Pass**
D.Sloane: 100.52 sec. 100% Accuracy (49/49 Targets) **Not Pass**

**Comment by Dimaslg** [comment]
Advanced Rifle Course Times:

20/06/2016
T.Müller: **84.676** sec. 98% Accuracy (49/50 Targets) **Pass**
J.James: 85.18 sec. 96% Accuracy (49/51 Targets) **Not Pass**

**Comment by Dimaslg** [comment]
MG Basic Course Times:

22/06/2016
K.Kresky: **63.3811** sec. **78%** Accuracy (150/192 Targets) **Pass**

**Comment by Dimaslg** [comment]
03/07/2016
MG Basic Course Times:
D.Gonzalo: **80.2932** sec. **81%** Accuracy (150/185) **Pass**

Advanced Rifle Course Times:
D.Gonzalo: **84.5139** sec. **98%** Accuracy (49/50) **Pass**

**Comment by SyMP2005** [comment]
@Dimaslg can you please edit your post per course?

Also, the noting will only happen when there is a top 3.

**Comment by Dimaslg** [comment]
I know the noting is just for the better three, but this is also a good way to keep a log of all the test we do. I can create another issue just for logging the tests If you dont want me to post them here.
- Basic MG
  K.Kresky - 63.3811 sec.
  D.Gonzalo - 80.2932 sec.
- Adv Rifle
  K.Kresky - 77.199 sec.
  R.Guldentops - 82.252 sec.
  D.Lopez - 82.574 sec.

**Comment by SyMP2005** [comment]
Yeah do that.

**Comment by SyMP2005** [comment]
Irrelevant at this point
