### ISSUE TITLE
fix the TAC flag on teleport flagpoles

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#47]
fucking bs

`Custom texture can be used, as long as it is in *.jpg format, and has dimensions of 200px*200px.`

works locally with PAA but not in multiplayer, wadda ya know....

**Comment by SyMP2005** [comment]
Fixed 8e847895610a4acf5b3cce594d2060c88a4c7cf3

**Comment by SyMP2005** [comment]
> Be very carful on MP servers with own textures. It seems that it is not enough to run local on server (e.g. via BIS_fnc_MP with [..,..,false,false]). Flags that are already in the game are no problem. But own textures (not important wether .jpg or .paa, I always prefer .jpg because they are much smaller) ONLY work when the mission is compressed into .pbo. That is important because many mission makers share and upload their missions as folders. Normally, that is no problem and works quite well, but in this special case, the server is not able to find the particular texture that is placed within a folder in the mission. That only works when mission is presented as .pbo. Failure: Warning Message: Cannot load texture mpmissions\v_02_[i_zg]uebungskarte.altis\pics\flags\flagge_aut.jpg. This you will get if mission is not uploaded as .pbo.

LMAO, no flags for us I guess!

**Comment by jonpas** [comment]
There is a similar problem with slideshow, I remember from testing way back now. It would work if you out the image in TAC Mods. Also, are you sure it doesn't work with setObjectTexture rather?

**Comment by jonpas** [comment]
Found the ticket for the issue https://feedback.bistudio.com/T80668

**Comment by SyMP2005** [comment]
Didn't test `setObjectTexture` yet.
That issue has been open for about 1.5 year now... :disappointed:

**Comment by jonpas** [comment]
Yes, so don't expect it to be fixed any time soon. As said, picture in a mod should work fine.

**Comment by SyMP2005** [comment]
So adding it to the modpack would fix it? (and using the right path of course.)

**Comment by jonpas** [comment]
Most likely.

**Comment by SyMP2005** [comment]
Works locally from modpack now. Since that should fix it in multiplayer as well, I'm closing this.
Reopen if problems.
