### ISSUE TITLE
Enhance urban area

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#50]
- [x] Targets on the street (Balcony target, obscured target in building)
- [x] Wreck on the street
- [x] Pop-up targets pop back up after like 3 seconds @jonpas? (This is done with the call `{ [_x, 0] call TACFUNC(shootingrange,animateTarget); } forEach _targets;`)

**Comment by jonpas** [comment]
> Pop-up targets pop back up after like 3 seconds @jonpas?

Shouldn't happen until you hit it (cause some damage on them). Maybe there is some damage taken during animation (if it goes through wall or something), you can add that to the loop where you animate the targets:
`_x setVariable [QTACGVAR(stayDown), true, true];`

And in `script_component.hpp`:

```
#define TACGVAR(var1,var2) TRIPLES(tac,var1,var2)
#define QTACGVAR(var1,var2) QUOTE(TRIPLES(tac,var1,var2))
```

**Comment by SyMP2005** [comment]
Indeed happens after they're shot down, forgot to mention that. Can that still be fixed with the loop?

**Comment by jonpas** [comment]
Yes, that will force it to stay down until manually put back up with animation (a courtesy of having a custom script running for popups - previously only a global variable could be used which forced all targets on map to act the same).

**Comment by SyMP2005** [comment]
ok thanks! :)
