### ISSUE TITLE
Enhance killhouse 1

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#51]
- [x] Remove one sandbag, at the end.
- [x] Possible double tap targets? @dimaslg

**Comment by Omnirock** [comment]
double taps shouldn't be encouraged as part of proper training.

**Comment by Dimaslg** [comment]
As I see it, a double tap drill not only complies with training procedures in real life environments but it's also a nice way to improve our awareness and attention to the weird behavior of the AI when wounded.

**Comment by Omnirock** [comment]
what training course uses "double tap" ? Proper training should involve controlled pairs. Double taps require one sight picture with two quick shots, it lacks control. Controlled pairs has you line up the sights on each shot, it can be done quickly with practice, and is much more reliable and safe than double taps. 

you need to be accountable for every single round that leaves your gun.

**Comment by SyMP2005** [comment]
I'm slightly confused now, are we still talking about hitting a target 2 times?

**Comment by Dimaslg** [comment]
At least I was.

**Comment by SyMP2005** [comment]
No double tap, closing this.
More discussing can be done in #59
