### ISSUE TITLE
Advanced Pistol Course

### ISSUE THREAD

**Issue by emythiel** [Theseus-Aegis/Olympus#59]
Been doing some runs in the Killhouse 1, which is what I recall we talked about using for the Adv. Pistol Course.

The course works fine from what I can see, and I overall like the course (with the exception of the one prone part - feels clunky. Doesn't mean it has to go though, that's just my personal preference)

For times and accuracy, I think either <45sec or <50 sec (or something between) and either >90% or >95% accuracy will work great.
90% acc allows you to miss twice, while 95% is only one miss.

@Omnirock @SyMP2005 @dimaslg

**Comment by emythiel** [comment]
Also forgot to mention that I've been trying with the P99 & the MP-443.
In general, I think a weapon with around 17 bullets such as those two or the Glock work well.

**Comment by SyMP2005** [comment]
Sounds good to me! Although I prefer that the used weapon is obtained from the certificate. For example here: a .45 Pistol. (Since those are the ones that will be unlocked.)

**Comment by emythiel** [comment]
Just tried it with the FNP45 Tactical, which has 15 bullets - still works well with the time at either 45 or 50 sec.

I would either remove or replace these 2 barrels:
https://i.imgur.com/1y3JzRX.jpg
Sometimes your bullet will ricochet and hit them, which causes them to burn. Looks weird :p

Edit: Just had Sverre Lodden run through it, and he very quickly reached a time of 47, so if we want to keep it difficult like with the Adv. Rifle course we could set time to 45 sec.

**Comment by SyMP2005** [comment]
https://github.com/Theseus-Aegis/Olympus/issues/60

**Comment by emythiel** [comment]
Did some quick runs on the course, and overall I like it.

For pistol, I think the FNP45 Tactical works perfect with its 15 bullets.
For time, I think 50 seconds would work well.
After a few attempts I got about 40s, and had Josuan try as well and he got 51 after 2 attempts or so.

For accuracy, I'm not sure yet, but thinking 90%.

**Comment by SyMP2005** [comment]
Sounds good, you wanna make that final @kresky?

**Comment by emythiel** [comment]
Yep, lets do it

**Comment by SyMP2005** [comment]
Waiting for new pistols... :(
