### ISSUE TITLE
Machine gunnner ammo request

### ISSUE THREAD

**Issue by Dimaslg** [Theseus-Aegis/Olympus#61]
In order to properly fulfil the machine-gunner position I hereby request that the Theseus Armory would be fitted with the equipment that follows:

For the RPK series
- RPK
- RPK12
- RPK-74

75 round magazines

For the HK416A5 14.5" series
- HK416A5 14.5" (Black)
- HK416A5 14.5" (Khaki)
- HK416A5 14.5" (Sand)

All kinds of magazines as the Armory doesn't shows any, specially drum magazines.

**Comment by SyMP2005** [comment]
All should be good now:
- Added 150rnd drum mag (HK416 14.5"). It had a wrong certificate linked, should be available now.
- All liqrzs weapons should've been available before.
- Added the 75rnd RPK magazine.
  
  @Dimaslg
