### ISSUE TITLE
Use Eden texture attribute for custom object textures

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/Olympus#67]
Instead of `this setObjectTexture [0, "texture.paa"];` in the init field use the new Eden object attribute for textures, added in Arma 3 v1.64.

**Comment by SyMP2005** [comment]
Currently only the sponsor signs have the option to add an object specific texture.
I'll leave this open because i'm hoping they'll add more!
GO BI!

**Comment by SyMP2005** [comment]
Also the laptops have it...

**Comment by jonpas** [comment]
Mind, this requires mission to be packed into PBO, due to https://feedback.bistudio.com/T80668.
Binarizing SQM during packing will also improve load times.
