### ISSUE TITLE
MG Course group suppression

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#68]
@kresky mentioned this:
- Have a secondary / mixed area with groups of enemies that can be controlled by an instructor.
- The instructor would pop up the desired group and the trainee would have to suppress all targets.
- The instructor is in full control of the completion for this course.

Thoughts?

**Comment by SyMP2005** [comment]
@jonpas @kresky

The group suppression works with the module! 
Targets pop up per group & go down after 4 hits (can be changed of course).

Only problem is that the popup are not random. We can choose the order however.
Thoughts?

**Comment by emythiel** [comment]
Randomly choosing which group would pop up would obviously be neat, but main focus should be kept on the suppression, so choosing our own order isn't a problem to me.

**Comment by jonpas** [comment]
https://github.com/Theseus-Aegis/tac-a3-mods/issues/190 - need my SQF Contractors!

**Comment by SyMP2005** [comment]
@kresky, your "own order" is not possible with multi-hit.
But since you said that's buggy anyway, I can do it differently, instead of the same order every time and multi hits:

-Single hit and being able to pop up whichever zone you want to. The targets will go down after **one hit** and will **remain down until a new zone has been selected**

How does that sound? It would work the same way as the new grenade course.
That's also something new to check out! 😄

**Comment by emythiel** [comment]
Worth a shot. It shouldn't be a problem that they go down after one hit, main focus should still be on suppressing the targets, and if you just one-tap targets one by one, the instructor can say it's not how it's supposed to be done :^)

**Comment by SyMP2005** [comment]
ok i'll update
