### ISSUE TITLE
Movement course / drivers license course timer

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#7]
Simple in-game timer to see how long it took the player to complete the course.
If possible, a triggers system that can be used for both courses and possible others in the future.

[fn_courseMove.txt](https://github.com/Theseus-Aegis/Olympus/files/233330/fn_courseMove.txt) (Your old script from UTG, perhaps useable...)

**Comment by SyMP2005** [comment]
Old script used, @jonpas does not approve.

**Comment by jonpas** [comment]
:hamster: :hammer:
