### ISSUE TITLE
Update times  for all stamina related courses 

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#70]
# Wait for definitive stamina settings
- The new stamina system is pretty brutal, certain times are not realistic anymore.
- [x] Advanced Rifle => +10 seconds
- [x] Movement Course => +10 seconds
- [x] Pistol course => +10 seconds

**Comment by SyMP2005** [comment]
@kresky, thoughts?

**Comment by emythiel** [comment]
Looks fine to me, although if we do go through with removing the prone part of the advanced rifle course, I'd probably wait with increasing the time until we see how much time is saved from the removal.

**Comment by jonpas** [comment]
When I will add the event on shooting range start, those variables have to be reset for full stamina reset, meaning you will always start the course with same stamina:
https://github.com/acemod/ACE3/blob/master/addons/advanced_fatigue/functions/fnc_handlePlayerChanged.sqf#L36-L40
