### ISSUE TITLE
Marksman Course

### ISSUE THREAD

**Issue by emythiel** [Theseus-Aegis/Olympus#77]
Currently testing these settings: (Basic marksman course)
Weapon: M14(Bipod/RIS)
Scope: MOS
Stance: Prone
Mode: Hit (Target Limit)
Targets: 30
Countdown: 15

No time requirement. Thinking completion should be around 70%-80% accuracy requirement at the moment, but will try and get some others to try it to see how it would be.

Suggestion:
There's currently 2 armory boxes there. Right now the plan would be to have both basic and advanced marksman be at the tower, so I'd suggest making the 2 boxes contain seperate gear (1 contains the basic marksman stuff, the other advanced).
Could mark it with some text on the crates as well like this:
https://i.imgur.com/2VAVJsA.jpg

Important note:
I noticed both the 2D and PIP variant of the MOS scope doesn't have correct magnification.
Hovering over them in your inventory will tell you it's 5x like the regular MOS, but the zoom itself is about the same as the 20x scopes.
I'd suggest completely removing 2D and PIP variants for now, both from the armory boxes on the tower as well as from the armory on the website so people can't buy them.

**Comment by emythiel** [comment]
Basic Marksman Certificate:

**Weapon:** M14(Bipod/RIS) - MOS Scope
**Stance:** Prone
**Mode:** Hit (Target Limit)
**Targets:** 30
**Countdown:** 15
**Accuracy:** 70%

No time requirement.

The armory boxes needs to have their equipment updated.
Until advanced marksman is finished, we can just have both armory boxes contain the basic equipment, as we sorted out in the google doc:
https://docs.google.com/spreadsheets/d/1UEoHvnsN255v9IP2eNzSJlsP_hzN5JSi-JNNmrOxH60/

Remember to not include the 2D and PIP variants due to magnification issues.

@SyMP2005

**Comment by SyMP2005** [comment]
gotcha

**Comment by emythiel** [comment]
After some more runs, Mike and I agreed on upping accuracy up to 80%.
In the end 70% ended up seeming a bit too lot. When Sverre, Mike and I took the course we all hit over 80% without trouble.

**Comment by SyMP2005** [comment]
alright done, will be updated on next modpack update
