### ISSUE TITLE
Medical training module

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#8]
![medical module](http://puu.sh/ot8oy/43c52db577.jpg)

As you suggested, a TAC medical module!

Todo:
- [ ] Make module
- [x] Define wounds, damages, etc in `fn_startMedicalExercise`

**Comment by jonpas** [comment]
I will be making a framework like shooting range in TAC  Mods, probably sometime this week.

**Comment by SyMP2005** [comment]
:+1:

**Comment by SyMP2005** [comment]
@jonpas:

https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_addDamageToUnit.sqf
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_addHeartRateAdjustment.sqf
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_adjustPainLevel.sqf
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setCardiacArrest.sqf
https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setUnconscious.sqf

Besides all that, is there a list of wound types like `bullet` & `stab` to set in `fn_startMedicalExercise.sqf` ?

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/blob/03f3b1084d4e9d14617f159db14a7086b1af8682/addons/medical/ACE_Medical_Treatments.hpp#L638-L691

**Comment by SyMP2005** [comment]
@jonpas:

I've tried to set these settings: https://github.com/Theseus-Aegis/Olympus/blob/fnMedicalExercise/functions/fn_startMedicalExercise.sqf#L57-L68

However, most of these damage sources seem to end up as `cuts`, resulting in some bodyparts having 3x Cut. I'm a bit confused to why it is doing this.

So in that regard, can the actual wound be set to the victim instead of the source it comes from?

**Comment by jonpas** [comment]
Different damage sources inflict different wounds and you are applying a bunch of damage, resulting in multiple wounds. I think you just have to experiment a bit, or jump on ACE3's Slack and ask.

**Comment by SyMP2005** [comment]
@jonpas can you change the medical exercise script so that the AI is spawned on interaction?

Right now, the placed AI wanders off sometimes...

**Comment by SyMP2005** [comment]
@jonpas, you still think this is something you'll be working on?

**Comment by jonpas** [comment]
One day, possibly. That doesn't mean you can't do your own thing in the mean time. ;)

**Comment by SyMP2005** [comment]
Hahaha
My own things... :disappointed:

**Comment by SyMP2005** [comment]
This has become redundant.
