### ISSUE TITLE
Movement course whiteboard

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/Olympus#80]
- [x] Timer does not start on initial vault, but there is a countdown
- [x] Timeout is set to 70 seconds, requirement to pass is <85 seconds (set in init of interactable object where you start the timer) -> #84

**Comment by SyMP2005** [comment]
What exactly do you want me to do with the whiteboard?

**Comment by SyMP2005** [comment]
Disregard, you want me to change the picture :D

**Comment by SyMP2005** [comment]
https://github.com/Theseus-Aegis/tac-a3-mods/pull/312
