### ISSUE TITLE
Advanced Rifle Course

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/Olympus#9]
As discussed with @Omnirock:

**INFO**
Advanced Rifle course (for advanced rifle certificate):
- Rifle course with movement.
- Moving from cover to cover.
- Shooting pop-up targets in the process.
- Identifying non targets in the process.

**To do:**
- [x] Find suitable location on Stratis.  
  (GR 520-500) Marked "Advanced Rifle Course"
- [x] Create Layout for the course.
- [x] Add enemy pop up targets.
- [x] Add friendly pop up targets.

**Comment by SyMP2005** [comment]
@Omnirock you think this would be large enough? Idea would be to "clear" the compound.

**Comment by Dimaslg** [comment]
After some time on the range, I love it Rory, I thought it would feel too tight and compress but It doesn't, I really love it, very good job. 

By now I got this times:
TIME/ACCURACY%
D.Gonzalo: 95/83%  89/80%  85/75%  91/85%  86/87%  **84/100%**
C.Kresky: 82/98%  83/95%  91/93%  82/100%  80/100%  79/98%  80/100%  **78/100%**
J.James: 94/95%  94/100%  91/98%  88/98%  **85/98%**  86/98%  87/100%
T.Muller: 126/93%  117/91%  100/95%  103/95%  99/95%  97/100%  99/93%  **95/98%**
D.Lopez: 87/98%  84/83%  **85/91%**  86/91%  93/93%  86/89%

And got this temporary settings:

```
- Weapon used: Colt M4 CQBR with Aimpoint.
- Stance: On the move, designated by instructor/signals.
- Mode: Hit (All targets)
- Targets: 40 (All)
- Countdown: 6s (Get it fixed)
- Pause duration: N/A
- Completion: <¿85/90? TBD secs & >90% accuracy.
```

To be able to get the Certification candidates must be PFC or higher rank, in possession of the basic rifle, pistol and grenade certifications and with at least five official missions played.
During the tests, the instructor will be following the candidate inside the range, keeping the distance and watching that he engage the targets in the correct stance. Wrong stances could end in time penalties or the stop and disqualify of the candidate, at judge of the instructor. (Only the candidate and the instructor would be allow inside the range during the test)

**_Everything I wrote could be subjected to changes depending on future tests or evaluations._**

Suggestions and ideas.
- Could it be possible to randomize the "friendly" targets? 
- Evaluate and test the Double tap setting for at least some of the targets.
- Fix all the settings on the computer so you can just start/stop it.
- Maybe too many jumps?
- And... what about change the name for Advanced Weapons Certification? So in the end you get advanced rifle and advanced pistol. I would like to see a transition from rifle to pistol and come back to the rifle, the center of the course suits perfect for that, if we get some smaller targets there. In the end we arrange two advanced certs in one and it could get a bit harder the test. (Could elaborate with pictures or in-game if needed)

**Comment by SyMP2005** [comment]
Nice write-up!

> To be able to get the Certification candidates must be PFC or higher rank, in possession of the basic rifle, pistol and grenade certifications and with at least five official missions played.
> During the tests, the instructor will be following the candidate inside the range, keeping the distance > and watching that he engage the targets in the correct stance. Wrong stances could end in time
> penalties or the stop and disqualify of the candidate, at judge of the instructor. (Only the candidate 
> and the instructor would be allow inside the range during the test)

**In regards to the requirements:** 
- Basic rifle => Yes
- Basic pistol => No
- Grenades => No  
  Both pistol and grenades are optional certificates and I don't wanna go to complicated on prerequisites. Rank requirement and the basic variant of the certificate will suffice.

The following of the candidate is a brilliant idea. I like it. Simple disqualification will do, if the course was executed incorrectly.

> - Weapon used: Colt M4 CQBR with Aimpoint.
> - Stance: On the move, designated by instructor/signals.
> - Mode: Hit (All targets)
> - Targets: 40 (All)
> - Countdown: 6s (Get it fixed)
> - Pause duration: N/A
> - Completion: <¿85/90? TBD secs & >90% accuracy.
- I could be wrong, but I think all settings are irrelevant since the mode is `trigger` based. @jonpas?  
- For countdown you want 6 seconds? Or what is wrong with it? Referring to the `(get it fixed)` 

> Could it be possible to randomize the "friendly" targets?

@jonpas? Even if possible that would make yet another mod. I would do with what we have ATM.

> Evaluate and test the Double tap setting for at least some of the targets.  

Let me know which targets you want to have double tap setting. I'll set it up.

> Fix all the settings on the computer so you can just start/stop it.

Again, settings on the computer will be set correctly by default, I don't think you can change anything except maybe countdown time.

> Maybe too many jumps?

Four jumps on the entire course... You'll jump! :smile:

**Comment by jonpas** [comment]
> I could be wrong, but I think all settings are irrelevant since the mode is trigger based. @jonpas?

Yeah, it's all automatically defined as it is expected all targets are to be shot that are set in the module.

> Could it be possible to randomize the "friendly" targets?
> @jonpas? Even if possible that would make yet another mod. I would do with what we have ATM.

It surely is possible, though I didn't come up with a viable solution yet. Most likely possible with an "onStart" code, but that would involve a lot of array swapping.

**Comment by SyMP2005** [comment]
Yeah, up to you (of course) if you wanna got there!

**Comment by Omnirock** [comment]
Been toying with different options in getting a working randomization for targets. 

I have two options now, one is randomization on start of mission: The targets will be random each time the mission is loaded, and this one so far works without errors. The second: Randomization on each run, which seems to be causing some issues with "invalid targets" on valid targets as well. 

Also trying to find a viable solution to the moving targets and targets on rails as well, but syncing with MP is the main issue with those.

**Comment by jonpas** [comment]
> I have two options now, one is randomization on start of mission: The targets will be random each time the mission is loaded, and this one so far works without errors. The second: Randomization on each run, which seems to be causing some issues with "invalid targets" on valid targets as well. 

Yes, the first one will work well, assuming you call the `tac_shootingrange_fnc_create` at the end instead of using a module. The second won't work because of the order targets are set and randomization will change that order.

> but syncing with MP is the main issue with those. 

Yes, it's currently impossible to do without huge network impact.

**Comment by Dimaslg** [comment]
Forget about the countdown thing Rory, for fixed I was meaning to get it hardcoded and just get a Start/stop button on the computer, but thats already in. So, my bad on that.

Double tap targets: http://imgur.com/a/eYkXA
- Too many jumps. I know some jumps are map limitations, but you added one more where I got stucked/glitched. Arma is not so friendly with jumping.

**Comment by SyMP2005** [comment]
Which jump do you wanna get rid of?

**Comment by Dimaslg** [comment]
All?

**Comment by SyMP2005** [comment]
Ok, i'll remove all.

EDIT: ended up keeping one and the initial one to vault / jump over when you start the course (it'll be good to define the start of the course.)

**Comment by SyMP2005** [comment]
Added multi-hit supported targets as requested.

**Comment by SyMP2005** [comment]
@Dimaslg, note final settings here please!

**Comment by Dimaslg** [comment]
**Advanced Rifle Course**

```
- Weapon used: Colt M4 CQB-R with Aimpoint CompM2 Red Dot 
- Stance: On the move
- Mode: Hit (All targets)
- Targets: N/A
- Countdown: 6 secs
- Pause duration: N/A
- Completion: <85 secs & >95% accuracy. 
```

Got the accuracy a bit higher, but we want this to be challenging. Im gonna give it some runs and get some times for my self.

Times from yesterday:
TIME/ACCURACY%
D.Gonzalo: 86.3/94% 86.1/96% 92.1/91% **84.2/94%**
K.Kresky: 81.9/98% 83.1/98% 82.1/94% 78.9/100% **77.3/100%** 78.1/96%
T.Muller: 89.8/96% 94/86% 91.8/96% 92.9/96% **87/98%** 90/98% 89/92%
R.Guldentops: 88/89% **86/98%** 88/94%

**Comment by SyMP2005** [comment]
Kresky cheats.
