### ISSUE TITLE
Ammo in the ACE Arsenal does not show up

### ISSUE THREAD

**Issue by JoramD** [Theseus-Aegis/Olympus#94]
**Arma 3 Version:** `1.80` (stable)
**Theseus Inc. Modpack Version:** `latest`
**Olympus Version:** `1.4.1` (stable)

**Mods:**
```
- Theseus Inc. Modpack
```

**Description:**
- When you take out a rifle in the restricted arsenal the ammo does not show up in the ammo tab but it does show up in the "all ammo types" tab. This does not happen with all rifles (IE: G36 ammo works) but it does on some others (IE: colt carbine AR15 .300 dissipator).

**Steps to reproduce:**
- Go in to the arsenal boxes, take out a colt carbine, go to your uniform and check the ammo tab. (Issue with several rifles this is just an example)

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer)

**RPT log file:**
- [gist](https://gist.github.com/JoramD0/926d8fceb63cc450f1030787f5081dcd)

**Comment by alganthe** [comment]
Fixed already:
https://git.io/vpIGs
